Day-27(Django)/pollapp/pollapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('polls.urls'))
]

Day-27(Django)/pollapp/polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('polls/', views.polls, name='polls'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Day-27(Django)/pollapp/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Day-27(Django)/pollapp/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Question

def index(request):
    return render(request, "index.html")
def polls(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "detail.html", {"question": question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

Day-27(Django)/pollapp/polls/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Poll app</title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cyborg/bootstrap.min.css" integrity="sha384-nEnU7Ae+3lD52AK+RGNzgieBWMnEfgTbRHIwEvp1XXPdqdO6uLTd/NwXbzboqjc2" crossorigin="anonymous">
  </head>
  <body>

    {% include 'navbar.html' %}
    
    {% block content %}
    
    {% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

Day-27(Django)/pollapp/polls/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <h3>{{ question.question_text }}</h3>
    {% for choice in question.choice_set.all %}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<div class="form-check">
            <input class="form-check-input" type="radio" name="choice" value="{{ choice.id }}">
            <label class="form-check-label" for="choice">
                <input type="radio" name="choice" value="{{ choice.id }}"/>
                {{ choice.choice_text }}<br>
            </label>
          </div>        
    {% endfor %} <br><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="button" class="btn btn-outline-info">Vote</button>&nbsp;&nbsp;&nbsp;
    <a href="{% url 'detail' question.id %}">Vote again?</a>
{% endblock %}

Day-27(Django)/pollapp/polls/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">Welcome to PollsterHub</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">PollsterHub is your go-to platform for simple and engaging polls. Whether you're looking to gather opinions, make decisions, or just have fun, our easy-to-use interface allows you to create and vote in polls effortlessly. Join our community, participate in ongoing polls, and see what others think on a variety of topics. With PollsterHub, your voice counts!</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a href="/polls"><button type="button" class="btn btn-primary btn-lg px-4 gap-3">Polls</button></a>&nbsp;&nbsp;&nbsp;
        <a href="/admin"><button type="button" class="btn btn-outline-secondary btn-lg px-4">Admin Panel</button></a>
      </div>
    </div>
  </div>

{% endblock %}

Day-27(Django)/pollapp/polls/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Poll app</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/polls">Polls</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin">Admin Panel</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Sports</a></li>
            <li><a class="dropdown-item" href="#">General Knowledge</a></li>
            <li><a class="dropdown-item" href="#">Politics</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

Day-27(Django)/pollapp/polls/templates/polls.html
{% extends 'base.html' %}
{% block content %}

  <header class="masthead">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center mx-auto">
          <div class="site-heading">
            <h3 class="site-heading my-4 mt-3 text-black">Welcome to My Poll App</h3>
            <p class="text-dark">This is my first django poll project</p>
          </div>
        </div>
      </div>
    </div>
  </header><br><br><br>
  
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock %}